print ("Введите ФИО:")
FIO = input()
print ("Введите факультет:")
FAC = input ()
print ("Введите курс:")
COURSE = input()
print ("Введте группу:")
GROUP = input()
print ("Введите e-meil:")
EMAIL = input()
print ("Студент(-ка) -", FIO, "обучается на факультете", FAC, ",на", COURSE, "курсе", ",находится в группе", GROUP, ",его/её e-mail:", EMAIL, end= '')
